import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// ─── Types ──────────────────────────────────────────────────────────────────────

export interface ReportData {
  userName: string;
  generatedDate: string;
  footprint: {
    totalKg: number;
    offsetKg: number;
    netKg: number;
    totalTons: number;
    offsetTons: number;
    netTons: number;
  };
  breakdown: Array<{ category: string; kg: number; value: number }>;
  monthly: Array<{ label: string; kg: number }>;
  recentActivities: Array<{
    category: string;
    description: string;
    co2Kg: number;
    date: string;
  }>;
  goals: Array<{ title: string; targetCo2Kg: number; deadline: string }>;
  offsets: Array<{ provider: string; co2Kg: number; date: string }>;
  monthlyLimitKg: number;
}

// ─── Brand Palette ──────────────────────────────────────────────────────────────

const COLORS = {
  darkEmerald: [5, 46, 33] as const,
  emerald: [16, 185, 129] as const,
  lightGreen: [52, 211, 153] as const,
  white: [255, 255, 255] as const,
  dark: [15, 23, 42] as const,
  gray: [100, 116, 139] as const,
  lightGray: [248, 250, 252] as const,
  mediumGray: [226, 232, 240] as const,
  categoryColors: {
    transport: [59, 130, 246] as const,
    energy: [245, 158, 11] as const,
    diet: [16, 185, 129] as const,
    waste: [6, 182, 212] as const,
  } as Record<string, readonly [number, number, number]>,
};

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const MAX_Y = 272; // leave room for footer

type RGB = readonly [number, number, number];

// ─── Helpers ────────────────────────────────────────────────────────────────────

function setColor(
  doc: jsPDF,
  color: RGB,
  type: 'fill' | 'text' | 'draw' = 'text',
): void {
  const [r, g, b] = color;
  if (type === 'fill') doc.setFillColor(r, g, b);
  else if (type === 'draw') doc.setDrawColor(r, g, b);
  else doc.setTextColor(r, g, b);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
}

function drawRoundedRect(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
  fillColor: RGB,
): void {
  setColor(doc, fillColor, 'fill');
  doc.roundedRect(x, y, w, h, r, r, 'F');
}

function drawSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  setColor(doc, COLORS.dark);
  doc.text(title, MARGIN, y);

  // accent underline
  setColor(doc, COLORS.emerald, 'draw');
  doc.setLineWidth(0.6);
  doc.line(MARGIN, y + 2, MARGIN + doc.getTextWidth(title), y + 2);

  return y + 10;
}

function drawFooter(doc: jsPDF, date: string): void {
  const footerY = PAGE_HEIGHT - 15;

  // thin emerald line
  setColor(doc, COLORS.emerald, 'draw');
  doc.setLineWidth(0.4);
  doc.line(MARGIN, footerY - 3, PAGE_WIDTH - MARGIN, footerY - 3);

  // footer text
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  setColor(doc, COLORS.gray);
  const footerText = `Generated by EcoAware Carbon Tracker \u2022 ${date}`;
  const fw = doc.getTextWidth(footerText);
  doc.text(footerText, (PAGE_WIDTH - fw) / 2, footerY);
}

/** Checks if we need a new page; if so, adds one + footer on previous page + returns reset Y */
function ensureSpace(
  doc: jsPDF,
  currentY: number,
  needed: number,
  date: string,
): number {
  if (currentY + needed > MAX_Y) {
    drawFooter(doc, date);
    doc.addPage();
    return 20;
  }
  return currentY;
}

// ─── Main Generator ─────────────────────────────────────────────────────────────

export async function generateCarbonReport(data: ReportData): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  doc.setFont('helvetica');

  const { generatedDate } = data;

  // ── Header Banner ───────────────────────────────────────────────────────────
  const bannerH = 55;
  setColor(doc, COLORS.darkEmerald, 'fill');
  doc.rect(0, 0, PAGE_WIDTH, bannerH, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  setColor(doc, COLORS.white);
  doc.text('ECOAWARE', MARGIN, 22);

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.lightGreen);
  doc.text('Carbon Footprint Report', MARGIN, 32);

  // User name
  doc.setFontSize(9);
  setColor(doc, COLORS.white);
  doc.text(`Prepared for: ${data.userName}`, MARGIN, 42);

  // Date right‑aligned
  doc.setFontSize(8);
  setColor(doc, COLORS.white);
  const dateStr = generatedDate;
  const dateW = doc.getTextWidth(dateStr);
  doc.text(dateStr, PAGE_WIDTH - MARGIN - dateW, 22);

  // Accent line
  setColor(doc, COLORS.emerald, 'draw');
  doc.setLineWidth(1);
  doc.line(0, bannerH, PAGE_WIDTH, bannerH);

  // ── Section 1: Summary Metrics ──────────────────────────────────────────────
  let y = 65;
  y = drawSectionTitle(doc, 'FOOTPRINT SUMMARY', y);

  const boxW = 55;
  const boxH = 40;
  const boxGap = (CONTENT_WIDTH - boxW * 3) / 2;
  const boxes: Array<{
    label: string;
    value: string;
    color: RGB;
  }> = [
    {
      label: 'Total Emissions',
      value: `${data.footprint.totalKg.toLocaleString()} kg`,
      color: COLORS.dark,
    },
    {
      label: 'Total Offset',
      value: `${data.footprint.offsetKg.toLocaleString()} kg`,
      color: COLORS.emerald,
    },
    {
      label: 'Net Footprint',
      value: `${data.footprint.netKg.toLocaleString()} kg`,
      color: COLORS.dark,
    },
  ];

  boxes.forEach((box, i) => {
    const bx = MARGIN + i * (boxW + boxGap);
    drawRoundedRect(doc, bx, y, boxW, boxH, 3, COLORS.lightGray);

    // border
    setColor(doc, COLORS.mediumGray, 'draw');
    doc.setLineWidth(0.3);
    doc.roundedRect(bx, y, boxW, boxH, 3, 3, 'S');

    // label
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    setColor(doc, COLORS.gray);
    const labelW = doc.getTextWidth(box.label);
    doc.text(box.label, bx + (boxW - labelW) / 2, y + 14);

    // value
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    setColor(doc, box.color);
    const valW = doc.getTextWidth(box.value);
    doc.text(box.value, bx + (boxW - valW) / 2, y + 28);
  });

  y += boxH + 6;

  // Monthly budget line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  setColor(doc, COLORS.gray);
  doc.text(
    `Monthly Carbon Budget: ${data.monthlyLimitKg.toLocaleString()} kg CO\u2082e`,
    MARGIN,
    y,
  );
  y += 12;

  // ── Section 2: Category Breakdown ───────────────────────────────────────────
  y = ensureSpace(doc, y, 60, generatedDate);
  y = drawSectionTitle(doc, 'EMISSIONS BY CATEGORY', y);

  const totalKg = data.breakdown.reduce((sum, b) => sum + b.kg, 0) || 1;
  const barMaxW = 90;
  const barH = 8;
  const barGap = 4;

  data.breakdown.forEach((item) => {
    y = ensureSpace(doc, y, barH + barGap + 2, generatedDate);

    const pct = Math.round((item.kg / totalKg) * 100);
    const barW = Math.max((item.kg / totalKg) * barMaxW, 2);

    // category label
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    setColor(doc, COLORS.dark);
    doc.text(capitalize(item.category), MARGIN, y + barH - 2);

    // bar background
    const barX = MARGIN + 35;
    drawRoundedRect(doc, barX, y, barMaxW, barH, 2, COLORS.mediumGray);

    // bar fill
    const catColor =
      COLORS.categoryColors[item.category.toLowerCase()] ?? COLORS.emerald;
    drawRoundedRect(doc, barX, y, barW, barH, 2, catColor);

    // percentage + kg
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    setColor(doc, COLORS.dark);
    doc.text(`${pct}%  (${item.kg.toLocaleString()} kg)`, barX + barMaxW + 4, y + barH - 2);

    y += barH + barGap;
  });

  y += 8;

  // ── Section 3: Monthly Trend ────────────────────────────────────────────────
  y = ensureSpace(doc, y, 140, generatedDate);
  y = drawSectionTitle(doc, 'MONTHLY EMISSIONS TREND', y);

  const chartH = 100;
  const chartW = CONTENT_WIDTH;
  const chartX = MARGIN;
  const chartY = y;
  const months = data.monthly;
  const maxKg = Math.max(...months.map((m) => m.kg), 1);
  const colW = months.length > 0 ? chartW / months.length : chartW;

  // light gridlines
  setColor(doc, COLORS.mediumGray, 'draw');
  doc.setLineWidth(0.15);
  for (let i = 0; i <= 4; i++) {
    const gy = chartY + chartH - (chartH * i) / 4;
    doc.line(chartX, gy, chartX + chartW, gy);
  }

  // bars
  months.forEach((m, i) => {
    const barHeight = (m.kg / maxKg) * (chartH - 15);
    const bw = colW * 0.5;
    const bx = chartX + i * colW + (colW - bw) / 2;
    const by = chartY + chartH - barHeight;

    drawRoundedRect(doc, bx, by, bw, barHeight, 1.5, COLORS.emerald);

    // kg value above bar
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6);
    setColor(doc, COLORS.dark);
    const kgText = m.kg.toLocaleString();
    const tw = doc.getTextWidth(kgText);
    doc.text(kgText, bx + (bw - tw) / 2, by - 2);

    // month label below
    doc.setFontSize(6);
    setColor(doc, COLORS.gray);
    const lw = doc.getTextWidth(m.label);
    doc.text(m.label, bx + (bw - lw) / 2, chartY + chartH + 5);
  });

  y = chartY + chartH + 14;

  // ── Section 4: Recent Activities Table ──────────────────────────────────────
  y = ensureSpace(doc, y, 40, generatedDate);
  y = drawSectionTitle(doc, 'RECENT ACTIVITIES', y);

  const tableRows = data.recentActivities.map((a) => [
    a.date,
    capitalize(a.category),
    a.description,
    a.co2Kg.toLocaleString(),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Category', 'Description', 'CO\u2082 (kg)']],
    body: tableRows,
    margin: { left: MARGIN, right: MARGIN },
    styles: {
      font: 'helvetica',
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: COLORS.darkEmerald as unknown as [number, number, number],
      textColor: COLORS.white as unknown as [number, number, number],
      fontStyle: 'bold',
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    didDrawPage: () => {
      drawFooter(doc, generatedDate);
    },
  });

  // Get y after autotable
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable
    .finalY + 10;

  // ── Section 5: Goals & Offsets ──────────────────────────────────────────────
  // -- Active Goals --
  if (data.goals.length > 0) {
    y = ensureSpace(doc, y, 30 + data.goals.length * 10, generatedDate);
    y = drawSectionTitle(doc, 'ACTIVE GOALS', y);

    const goalRows = data.goals.map((g) => [
      g.title,
      `${g.targetCo2Kg.toLocaleString()} kg`,
      g.deadline,
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Goal', 'Target CO\u2082 (kg)', 'Deadline']],
      body: goalRows,
      margin: { left: MARGIN, right: MARGIN },
      styles: {
        font: 'helvetica',
        fontSize: 8,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: COLORS.darkEmerald as unknown as [number, number, number],
        textColor: COLORS.white as unknown as [number, number, number],
        fontStyle: 'bold',
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      didDrawPage: () => {
        drawFooter(doc, generatedDate);
      },
    });

    y =
      (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable
        .finalY + 10;
  }

  // -- Logged Offsets --
  if (data.offsets.length > 0) {
    y = ensureSpace(doc, y, 30 + data.offsets.length * 10, generatedDate);
    y = drawSectionTitle(doc, 'LOGGED OFFSETS', y);

    const offsetRows = data.offsets.map((o) => [
      o.provider,
      `${o.co2Kg.toLocaleString()} kg`,
      o.date,
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Provider', 'CO\u2082 Offset (kg)', 'Date']],
      body: offsetRows,
      margin: { left: MARGIN, right: MARGIN },
      styles: {
        font: 'helvetica',
        fontSize: 8,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: COLORS.darkEmerald as unknown as [number, number, number],
        textColor: COLORS.white as unknown as [number, number, number],
        fontStyle: 'bold',
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      didDrawPage: () => {
        drawFooter(doc, generatedDate);
      },
    });
  }

  // ── Footer on final page ────────────────────────────────────────────────────
  drawFooter(doc, generatedDate);

  // ── Save ────────────────────────────────────────────────────────────────────
  const dateForFilename = generatedDate.slice(0, 10); // YYYY-MM-DD
  doc.save(`EcoAware_Carbon_Report_${dateForFilename}.pdf`);
}
